name: Build MX4300 FOSS Image

on: workflow_dispatch

jobs:
    build:
        name: Build MX4300 FOSS Images
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt-get install -y \
                      build-essential \
                      clang \
                      flex \
                      bison \
                      g++ \
                      gawk \
                      gcc-multilib \
                      g++-multilib \
                      gettext \
                      git \
                      libncurses-dev \
                      libssl-dev \
                      python3-distutils \
                      rsync \
                      unzip \
                      zlib1g-dev \
                      file \
                      wget && \
                  sudo apt-get clean

            - name: Checkout
              uses: actions/checkout@v4

            - name: Update feeds
              run:  scripts/feeds update -a && scripts/feeds install -a

            - name: Generate config
              run:  sh genconfig.sh

            - name: Generate defconfig
              run:  make defconfig

            - name: Build firmware images
              run:  make -j$(($(nproc)+1)) world
            
            - name: Prepare release
              run:  sh release.sh

            - name: Get SHA
              uses: benjlevesque/short-sha@v3.0

            - name: Release
              uses: ncipollo/release-action@v1
              with:
                tag: qualcommax-foss-${{ env.SHA }}
                artifacts: release/*
                bodyFile: note.md
