name: build foss snapshot node
on:
  workflow_dispatch:
  workflow_call:          
  
jobs:
  call-image-builder-foss-snapshot:
    permissions:
      contents: write
    uses:
      ./.github/workflows/image_builder_mod.yml
    with:
      build_settings: 
        '{"SOURCE_REPO":  "https://github.com/openwrt/openwrt.git", 
        "SOURCE_BRANCH": "main",
        "BUILD_REPO":    "https://github.com/${{github.repository}}.git",
        "BUILD_BRANCH": "build",
        "BUILD_INIT": "init_build.sh",
        "BUILD_TYPE":  "foss",
        "BUILD_CUSTOM": "node",
        "BUILD_VER": "snapshot",
        "BUILD_TAG": "",
        "BUILD_SYNC": "n",        
        "BUILD_KMOD": "y"}'
